version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tools
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  database: